### ISSUE TITLE
Darkmoon Deck: Fathoms missing on 1/20/2019

### ISSUE THREAD

**Issue by zerlure** [Bloodmallet/bloodmallet.github.io#135]
I was trying to compare my current trinkets to the raid trinkets and the Darkmoon deck was pretty high before, but it appears to no longer be on the list.

**Comment by Bloodmallet** [comment]
What itemlevel does the item have or can be crafted at/upgraded to?

**Comment by zerlure** [comment]
355

**Comment by Bloodmallet** [comment]
That's the reason then. 370 is the lowest cutof now.

**Comment by zerlure** [comment]
Is that going to be changed, or that just the way it's going to be?

**Comment by HawkCorrigan** [comment]
shamelessly plugging a discord post

![grafik](https://user-images.githubusercontent.com/2129161/51555624-51469600-1e78-11e9-8a6a-c8e3d9f5bc87.png)

**Comment by Bloodmallet** [comment]
Adding some more context:
```
Bloodmallet(EU)Today at 14:18
it's actually quite hard to fit such exception in, without screwing every user ^^'
of course! please ask and suggest stuff
this helps to improve the resource
major issue with a "special itemlevel" is, it would either require me to add that itemlevel to everything or it would be misunderstood
```

The major problem with a trinket like this is: it either would need to appear in the legend and everyone would wonder why only one trinket has that itemlevel available and would want to have that itemlevel simed for everything. which is a calculation requirement I'd like to avoid.
OR that item "looks" like a different itemlevel, but isn't. which would be even more confusing.

This item and the topic surrounding it is really difficult. I'd love have an easy solution but for now I can only leave it out. Calculation power is always a limiting factor.

**Comment by zerlure** [comment]
Thanks, I appreciate the well worded response. I just know that according to raidbots it's better than most 385 trinkets, was curious how it held up with 400. I'll just sim as I get new trinkets and figure it out myself.

**Comment by nzall** [comment]
What might be a solution is to have a "legacy" color. You might have this problem for the entire expansion, because from what I understand there were a couple of world boss trinkets that also simmed exceptionally well for some specs. Blizzard tends to be good at making most trinkets be similar DPS, but there are often a handful of items per expansion that have a particularly overpowered effect and eventually get nerfed because of it. I remember Draught of Souls and Convergence of Fates in Legion, Greatness in Wrath of the Lich King, most legendary weapons, Unerring Vision of Lei Shen in Mists of Pandaria, Dragonspine Trophy in TBC, Unheeded Warning in Cataclysm... Every expansion has a couple of these, so having a way to support exceptionally good trinkets from earlier tiers would be a good idea.

**Comment by Bloodmallet** [comment]
Going from a pure visual approach the "legacy" color makes sense. But that's not how the chart would actually work and show the data. These legacy trinkets would still show up with their appropriate itemlevel in the legend. Which would still create the same confusion. Or to play even more the devils advocate: What if next tier a 370 itemlevel trinket would need to stay in the chart as well. This would then probably force two legacy colors to ensure that the user knows that those two have different itemlevels.

I'd like to have a way to support special exceptions. I just don't know of a way right now. But maybe this discussion will polish for example your suggestion enough, so it'll see implementation. So please keep going with these ideas. We're just going through the process of improving them.
