### ISSUE TITLE
BM Hunter Azerit Item Patchwork lists items in 415 which are not existing in 415

### ISSUE THREAD

**Issue by Mercian** [Bloodmallet/bloodmallet.github.io#142]
**Describe the bug**
In the List for Azerit Items are items listed very High on ilvl 415 which are actually not available in 415. e.g. Shoulders: Ashenwood Spaulders, there is no way ot obtain this in ilvl 415. Also the followings. The sim result should display only items with available ilvl.

**To Reproduce**
1. Go to 'Hunter' --> Beast Master -->Azerite --> Shoulder--Patchwork
2. Ashenwood Spaulders is listed as first in ilvl 415. but it is not available in the game as 415. Same for the second listed item Sinister Gladiator's Chain Pauldrons.

**Expected behavior**
Sim result should list items only in available versions.

**Comment by Bloodmallet** [comment]
Greetings, thank you for creating this issue. This problem is on my to-do list for a long time already, but I didn't have the necessary time yet. To tackle this issue I'll need some sort of itemlevel mapping for **all**  items. As I'd need to create that by hand this issue was delayed and still has no ETA. I'll look into working on that in a future update.

**Comment by Mr-nUUb** [comment]
The same happens with marksman shoulders. Benthic 445? Not possible!
Benthic maximum item level is 430.
![benthic-445](https://user-images.githubusercontent.com/36689675/62659303-444c4880-b96b-11e9-911d-ee029f46ec24.png)

**Comment by eminorgh** [comment]
Yes, I'm having the same problem when trying to locate my BiS items.  Most items on these tables are not even available at the item level for the sims that are listed.  

Take the very first item on this table for example, Kaldorei Archer's Coif, which is listed as BiS single target... The sims are for 400, 415, 430 & 445 item levels but this item is ONLY available as a 355 item level in-game because it is a drop from a rare elite on Darkshore. 
<img width="1523" alt="Bloodmallet" src="https://user-images.githubusercontent.com/52894532/62823663-424bda80-bb61-11e9-8de3-c4b26a13ce5e.png">

**Comment by Bloodmallet** [comment]
The next data update in roughly 24h should have the first take on Azerite Item itemlevel sanity check. Please let me know if some items are still wrong.
