### ISSUE TITLE
iframe / embed support to share from the website

### ISSUE THREAD

**Issue by lcestou** [Bloodmallet/bloodmallet.github.io#147]
**Is your feature request related to a problem? Please describe.**

I tried to use bloodmallet and highcharts import charts in a Discourse site, but the ID and Class tags get stripped in the post content after is posted and therefore it makes it non functional (won't load). It can be difficult to manage and get Discourse to not strip the HTML content when is processed.

**Describe the solution you'd like**

However, I can whitelist websites to allow an iframe/embed to be displayed.

I was wondering if the bloodmallet site can provide a share embed/iframe code to use on any website? I apologize if this feature is already implemented, I just couldn't find it.

Maybe have checkmarks of what to display on the embed, like only the charts instead of the whole page.

Other option it would be is to hook the scripts to something else other than id and class or optional data tags that replicate same ID and Class?
Currently Discourse post content does allow the data tags and properties as those do not get stripped.

**Describe alternatives you've considered**

I am thinking to override with plugins for the Discourse site, but installing a plugin requires taking the site down temporarily to rebuild the app every time something changes in the plugin.

I can also make my own iframes to work, but that would get muddy when other people would try to share their own and would have to make a tutorial, etc.

**Additional context**

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out about this issue. If possible, I'd like to support your case.

Do your stripped divs get a new id (just not the one you added yourself?)? Without any ID this whole issue becomes a real pain (because I lack iframe experience and therefore wouldn't want to go that way. If anyone is able to provide a pullrequest to support iframes, that would be great). I know from this [fiddle](http://jsfiddle.net/gh/get/jquery/1.7.1/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/renderto-jquery/) that highcharts can work without IDs, but based ont hat fiddle jquery would be necessary...? It would need a lot more research.

Tricky but great question!

**Comment by lcestou** [comment]
Thanks for the quick response.

It does not add any id or class at all. It removes them completely, it doesn't replace them with a different one (I know it sucks).

The only way right now that I can think of to target those divs are by using similar to css targeting by attribute:

[attribute~="value"]

I know that makes it a pain but at least it would make it agnostic, instead to depend on an ID or class to trigger it and can use a generic method like targeting data attributes to activate it if they exist.

I wish they wouldn't stripped the code by default. Which I find very odd they allow certain HTML things at the user post field, but basic things like ID or class are not. Doesn't make much sense in my head, but they must have a reason behind it.

Trying to use it here on my website:
https://wowlazymacros.com/t/blood-mallet-script/6953

But as you can see if inspect the "Loading", the ID and class are missing. I disabled the scripts for now on the back end since they would load for nothing until I can fix this issue.

Thanks again!

**Comment by Bloodmallet** [comment]
While I want to make the importer as flexible as possible, I want to emphasize at this point, that I'm strongly against anything that goes against Blizzard/WoW Terms of Service.

Nonetheless I image the raised issue could potentially affect many. So an update to the importer will go out soon.

`data-bloodmallet="chart"` will become a valid attribute. Any element with this attribute will be used to add a chart to it, exactly like the css class works right now. I'll update the wiki in a minute.

("chart" was used as value, because who knows what other importables might come in handy in the future. like discord links or so)

**Comment by lcestou** [comment]
Awesome Bloodmallet,

If you are referring if wow lazy macros might be illegal do not fear, there has been a misconception for the past 8 years about it. But we even have had official wow GM's in the community and many instances where they back us up.

Also using macro keyboards is allowed by Blizzard and combination with the macro add-ons also. People have never got banned for using our site, if someone claims that they might of is because they were probably botting or doing something not acceptable unrelated to wow lazy macros :)

I will test as soon as I can as I'm traveling at the moment, thanks again!
