### ISSUE TITLE
Marksmanship Hunter & Essence of the Focusing Iris minor

### ISSUE THREAD

**Issue by AirflashX** [Bloodmallet/bloodmallet.github.io#159]
**Describe the bug**
When i look at minor essences for Hunter: Marksmanship at the "Essence of the Focusing Iris minor", rank 3 does less dps then rank 2. Is this even possible? oO

In the list:
Rank 2: 1.106 dps
Rank 3: 1.081 dps

**Comment by Bloodmallet** [comment]
Greetings, thank you for reaching out. If in any chart a change to the profile yields a result within target error, the resulting dps of the "higher/better" item can be a slightly lower dps. That's just within target error and absolutely normal. This usually happens when the higher itemlevel or rank no longer actually provides any dps benefit.
