### ISSUE TITLE
azerite power weights

### ISSUE THREAD

**Issue by Addonman** [Bloodmallet/bloodmallet.github.io#160]
**Is your feature request related to a problem? Please describe.**
Why 2  lists for APW -1 for essences and 1 for azerite?Now i have to swithc between 2 of them when i want something
**Describe the solution you'd like**
1 list with both azerite and essences on it.

**Comment by Bloodmallet** [comment]
Greetings,
due to the way the weights are generated I'm not easily able to create a combined string. Sorry about the inconvenience. If someone would like to, they could try writing this as a pull request. I'll help with the procedure and where to start for this feature.

**Comment by Addonman** [comment]
Being using this page for while.
https://github.com/ahakola/AzeritePowerWeights/blob/master/ImportStringHelp.md

Its just matter of pasteing essences behind azerite  string.

**Comment by Bloodmallet** [comment]
Yes, that's what needs to be done. Right now each import string is prepared by the backend (in those fixed files which are used for the charts). The issue is, that essences and azerite traits are simulated in different steps of the procedure, which allows only access to either data when each file is generated. Meaning the front-end would need to load the data file, even though the user hasn't viewed the chart of that yet. which in turn would increase the necessary download for the page to function properly. Which I'm not a fan of either. BUT it's technically possible, which is why I welcome everyone to play around with it and ideally create a pull request.
