### ISSUE TITLE
BloodMallet incorrect trinket

### ISSUE THREAD

**Issue by MadJeff2k19** [Bloodmallet/bloodmallet.github.io#169]
Hi,

I was just looking at Single target trinkets for Havoc demon hunter and came across this 
![image](https://user-images.githubusercontent.com/59944788/72487723-d738bb00-3806-11ea-8e79-e304e090714a.png)

Psyche Shredder is an intellect trinket
https://www.wowhead.com/item=174060/psyche-shredder&bonus=4822:1487#dropped-by

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out. This trinket was set to be simulated with ago and strength characters too, because as you can see it performs very well. Once there is a mechanic introduced to reduce its efficiency to a normal level for non-int characters, this trinket will be taken off the charts for non-int characters.
