### ISSUE TITLE
Add Tooltips to Items/Traits

### ISSUE THREAD

**Issue by Sinaloit** [Bloodmallet/bloodmallet.github.io#32]
Suggestion: Use http://www.wowhead.com/tooltips or something similar to provide tooltips on the leftmost edge of the charts for items/traits/crucible abilities.

**Comment by Bloodmallet** [comment]
I tried using that already, but I didn't manage to make highcharts chart generation enable such a thing. I'll have to try again (cause I think tooltips like this would be really cool)

**Comment by Bloodmallet** [comment]
After looking around further: the problem is that any kind of inserted link into the categories names are replaced by highcharts (and all other chart libs I looked into) with tspans and an onclick action that changes location to the link. Wowheads tooltip script doesn't recognise that and therefore no tooltip is visible.

**Comment by Bloodmallet** [comment]
OK there is a way to include item tooltips. Only problem: it breaks the background of the normal bar chart tooltips.

**Comment by Bloodmallet** [comment]
The next redoing of all charts with the probably new tuning, is going add tooltips to the page. (and potential fixes to maybe broken code i wrote blindly just now)

**Comment by Bloodmallet** [comment]
Tooltips are slowly rolling out.
