### ISSUE TITLE
azerite trait inconsistency for arms warrior

### ISSUE THREAD

**Issue by hevyxx** [Bloodmallet/bloodmallet.github.io#93]
when viewing viewing azerite trait stacking (simmed at ilvl 385), it says one test of might trait has a result of 640
while viewing azerite traits by ilvl- it says test of might at ilvl 385 results 983
not sure which number is correct
thanks

**Comment by Bloodmallet** [comment]
Greetings,
The itemlevel chart includes the value of the increased primary stats (str, agi, int) for the higher itemlevels than the baseline. Meaning: at 385 you not only get a stronger trait but the primary stats too.
The trait stacking chart doesn't have changing primary stats, because all different trait counts/sims use the same itemlevel. Therefore the primary stat value is excluded there.

I hope this answered your question.

**Comment by hevyxx** [comment]
It should say that- because test of light increases strength for a period
of time after colossus smash based on rage spent. If we are ignoring
strength how can you accurately aim test of might effectiveness

**Comment by Bloodmallet** [comment]
We might be talking about different things right now. If a trait adds primary stats, these stats are applied to the profile and used at the appropriate itemlevel.
By "excluding primaries" I was talking only about the already baseline stat increase you see on every item. Azerite Items offer stamina and agility/intellect/strength in addition to the trait circles.

**Comment by hevyxx** [comment]
Okay, so if the sim for trait stacking is run at 385- and I look at the sim
for trait ilvl. It’s very confusing to look at one trait and see a
different number on the trait ilvl at 385 vs one trait on the trait ilvl
chart. So which chart should I look at?

**Comment by Bloodmallet** [comment]
Depends on what you're looking for. The stacked trait chart offers you a view on how the value of a trait behaves when you stack it. 
Example:
![image](https://user-images.githubusercontent.com/9075987/44925385-9f82bd80-ad4e-11e8-8409-5dc62b550d72.png)
As you can see here: Ancestral Resoance is a very special trait which loses a lot of value when you stack it. So if you have to decide betwen having that trait three times, vs taking a different trait, it's quite likely that the different trait will be better. Glory in Battle on the other hand shows a steady grow. For that trait it doesn't matter how many you add, their worth is always the same.

Of course this chart is not enough if you're comparing traits on different itemlevels. For that you need to look at the `Itemlevel` chart. This chart shows you the worth of **ONE** trait at all these different itemlevels.

In the end, if the difference seems to be very small, then siming your char yourself is always the answer. General charts like mine can only help you so much. They are a great help to understand the general worth of something, but if it becomes a tight decision between multiple options only a simulation can truely tell, what's best.

**Comment by hevyxx** [comment]
It seems you’re still not quite seeing the issue that I’m dealing with.
Got to arms warrior sims- and view azerite traits by ilvl and trait stacking
If you look at Test of Might on the ilvl chart it says one stack will do
983 while on the trait stacking chart it reads 640.
That’s a 53% increase from one to the other (at a single ilvl) with no
explanation anywhere on the site when they should read the same number.
Thanks.

**Comment by Bloodmallet** [comment]
983 is the dps the trait and necessary item will give you, when you compare that to a baseline 340 traitless item. So the 983 dps is the sum of the trait power itself and the main stat gain from increasing the itemlevel of the item from 340 to 385.
Including the itemlevel increase of the item seems necessary because the chart compares itemlevels and those don't come for the trait only.

640 dps is the dps increase of a 385 trait on a 385 item compared to a traitless 385 item. Here you see the pure trait value.

I'm sorry, that I couldn't convey this better at first. If you have a suggestion on how to provide this information in a better way, please let me know. I hope this explanation was better now.

**Comment by hevyxx** [comment]
Thank you that makes sense
If you just say on the trait stacking is pure trait dps not including
mainstat increase- that will make the chart more clear
Thanks

**Comment by Bloodmallet** [comment]
Good idea. I'l lthink how to add that, without making the title too long.

Glad I could help.
