### ISSUE TITLE
Add chart marker choice

### ISSUE THREAD

**Issue by Velzar** [Bloodmallet/bloodmallet.github.io#97]
Add possibility to choose which chart marker to show. (e.g. trinket ilvl) For example if i want to compare only 370 trinkets and below.

**Comment by Bloodmallet** [comment]
You mean an itemlevel filter? Like a list where you tick which itemlevels to show?

- [ ] 340
- [ ] 355
- [ ] 370
- [ ] 385

**Comment by Velzar** [comment]
yes, but you tick on a markers in chart legend

**Comment by Bloodmallet** [comment]
The legend doesn't have that functionality. I'll need to write custom code for that, but yes I think I get, what you mean. This is already point in my todo list: https://github.com/Bloodmallet/bloodmallet.github.io/issues/81

**Comment by Velzar** [comment]
it has such finction, look here https://www.highcharts.com/demo/bar-stacked

**Comment by Bloodmallet** [comment]
That functionality doesn't work for the dps charts, because the used stacked charts aren't exactly used as they are intended.
Stacked charts work great and are intended for comparing the "size" of different things. So if you want to compare how many different fruits you have, you can compare them in a stacked chart, to have a visual indication of how much of your fruit count each fruit type makes up.
Apples 3, Banana 2, Cherry 4
For this example the length of the bar is 9 and each fruit type has the length of the fruit count within that bar. If you click ont he fruit type in the chart, like you linked it, that category disappears and the bar becomes shorter.
DPS charts don't work like this. Here the first category shows the full gain of a trinket/whatever. So if a trinket at 340 provides 340 dps, you see the appropriate length of 340 for that bar. Now the tricky part begins. The next bar section shows only the **gain** of the trinket from 340 to 355. So while the 355 version might do 355 dps, the actual section shows only 15 dps, because that's the difference between the two. This way you get one easily comprehendable big bar to see how one trinket develops over multiple itemlevels. If you simply disable the first itemlevel in this example, then the remaining dps value would be 15, which is of course wrong, but because of the necessary data format, would appear like this.

If there is a way to make highcharts automatically show the gain from one category to the other (itemlevel in this case) instead of showing the full number/length of the bar, then yes I could re-enable the legend click event. But until I find that, or I write my own filters, such a feature won't be available. If you know how to change highcharts to show the gain by itself, let me know.

**Comment by Velzar** [comment]
I understand your point, but you described exactly what is enough to do. Look here https://www.retpaladin.xyz/ret-paladin-8-0-1-pve-guide/
section "Trinket Rankings" (Ctrl+F).
The thing is, if you want to compare ilvl 370 and below trinkets, you should tick all the markers below it.
this functionality make possible to disable all higher ilvls.

**Comment by Bloodmallet** [comment]
I see what you mean. The main problem is, that not every user will indeed only deselect the higher itemlevels. If you're interested in comparing a 355 one to a 370 one, you want to disable all other itemlevels, not only 385. I want to offer such a filter in the future. Just the time to do so is missing right now.

**Comment by Velzar** [comment]
Roger that
